/cart/list.htm=cart.command.CartListHandler
/index.htm=command.MainHandler
/admin/createProduct.htm=admin.command.ProductCreateHandler
/admin/editProduct.htm=admin.command.ProductCreateHandler
/admin/deleteProduct.htm=admin.command.ProductDeleteHandler
/admin/userList.htm=admin.command.AdminUserListHandler
/admin/userDetail.htm=admin.command.AdminUserDetailHandler
/admin/productList.htm=admin.command.ProductListHandler
/admin/tagList.htm=admin.command.TagListHandler
/admin/createTag.htm=admin.command.TagCreateHandler
/admin/editTag.htm=admin.command.TagListHandler
/admin/toggleTag.htm=admin.command.TagListHandler


/admin/coupon_list.htm=admin.command.CouponListHandler
/admin/delete_coupon.htm=admin.command.CouponDeleteHandler
/admin/create_coupon.htm=admin.command.CouponCreateHandler

/product/product_detail.htm=command.ProductDetailHandler
/product/detail.htm =command.ProductDetailHandler
/product/list.htm=command.ProductListHandler
/search/record.htm=command.SearchHandler
/event/event.htm=event.EventHandler
/login.htm=command.LoginHandler
/logout.htm=command.LogoutHandler
/mypage.htm=mypage.MypageHandler

/mainGroupAjax.htm=command.MainGroupAjaxHandler




/inquiry/write.htm=mypage.MypageQnaHandler
/inquiry/list.htm=mypage.MypageHandler
