/index.htm=command.MainHandler
/admin/createProduct.htm=admin.command.ProductCreateHandler
/admin/userList.htm=admin.command.AdminUserListHandler
/product/list.htm=command.ProductListHandler
/product/product_detail.htm=command.ProductDetailHandler